name: build
on:
  pull_request
jobs:
  security_scan:
    runs-on: ubuntu-latest
    name: prisma-cloud-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
